### ISSUE TITLE
Clarification needed: '404 NOT FOUND' for class 15-19 notes in schedule 

### ISSUE THREAD

**Issue by emmagoodrich** [comp426-2022-fall/schedule#2]
Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

**I wasn't sure which template to use since this issue doesn't really fall into any of the 3 options**

#### URL of file with confusing thing
https://github.com/comp426-2022-fall/schedule/blob/main/15-endpoints.md#notes
https://github.com/comp426-2022-fall/schedule/blob/main/16-logs.md#notes
https://github.com/comp426-2022-fall/schedule/blob/main/17-database.md#notes
https://github.com/comp426-2022-fall/schedule/blob/main/18-users.md#notes

#### What is confusing?
I was hoping these could be uploaded so that I can reference them as I am completing the final coding assignments! For example, we did not finish the user endpoints in class and Professor Martin said he would upload the finished version, but I cannot access the notes from that class.

**Comment by jdmar3** [comment]
Apologies. This keeps falling off the top of the pile. I will work on it tonight and make sure that they are up.

**Comment by emmagoodrich** [comment]
I am still not able to access any of these, will they be up soon?

**Comment by jdmar3** [comment]
These should all be accessible from the Schedule page now.
